### ISSUE TITLE
has no method 'vgSwapBuffers'

### ISSUE THREAD

**Issue by nagualcode** [eendeego/node-openvg-canvas#29]
Hello, 
I can get the clock example running, but many other fails like:

/node-openvg-canvas/examples/pathText.js:107
canvas.vgSwapBuffers();
       ^
TypeError: Object [object Object] has no method 'vgSwapBuffers'
    at Object.<anonymous> (/root/node-openvg-canvas/examples/pathText.js:107:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by 2xAA** [comment]
Change those calls from "canvas.vgSwapBuffers();" to "Canvas.vgSwapBuffers();".
They're different variables.
