### ISSUE TITLE
Error installing in NPM

### ISSUE THREAD

**Issue by mitsukaki** [eendeego/node-openvg-canvas#31]
I get the following each time I try to install the openvg-canvas module. I'm not quite sure why it occurs.

```
lite@lite-pc:~/Documents/JaxRender$ npm install --save openvg-canvas
npm WARN package.json JaxRender@0.0.0 No description
npm WARN package.json JaxRender@0.0.0 No repository field.
npm WARN package.json JaxRender@0.0.0 No README data
    -
    > openvg@0.4.5 install /home/lite/Documents/JaxRender/node_modules/openvg-    canvas/node_modules/openvg
    > node-gyp rebuild

make: Entering directory '/home/lite/Documents/JaxRender/node_modules/openvg-canvas/node_modules/openvg/build'
CXX(target) Release/obj.target/init-egl/src/init-egl.o
../src/init-egl.cc:1:21: fatal error: EGL/egl.h: No such file or directory
    compilation terminated.
init-egl.target.mk:94: recipe for target 'Release/obj.target/init-egl/src/init-egl.o' failed
make: *** [Release/obj.target/init-egl/src/init-egl.o] Error 1
make: Leaving directory '/home/lite/Documents/JaxRender/node_modules/openvg-canvas/node_modules/openvg/build'
gyp ERR! build error 
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-18-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/lite/Documents/JaxRender/node_modules/openvg-canvas/node_modules/openvg
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! openvg@0.4.5 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openvg@0.4.5 install script.
npm ERR! This is most likely a problem with the openvg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openvg
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-18-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "openvg-canvas"
npm ERR! cwd /home/lite/Documents/JaxRender
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lite/Documents/JaxRender/npm-debug.log
npm ERR! not ok code 0
```

Thanks for the hand!

**Comment by fu-raz** [comment]
This was the same for me, I'm using v0.10.22 now and it is working now. I installed node using this simple guide:

http://doctorbin.tumblr.com/post/53991508909/how-to-install-the-latest-version-of-nodejs-npm

But then using http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-arm-pi.tar.gz in stead of v0.11.3 as they use in the guide

**Comment by mitsukaki** [comment]
Ah okay, thanks! @fu-raz

**Comment by F1LT3R** [comment]
I'm also having this error, but with Node `10.8.0`
